name: Setup
description: Download and install third-party software.
runs:
  using: composite
  steps:
    - name: Install Mise
      uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        version: 2026.7.7

    - name: Install Dependencies
      shell: bash
      run: >-
        pnpm install
        --frozen-lockfile
        --filter create-font-workspace
        --filter create-font
        --filter create-design
        --filter @create-art/source-format
        --filter @create-design/source
        --filter @create-font/server
        --filter @create-font/target
        --filter @create-font/states
        --filter @create-font/source
        --filter @create-font/fea-wasm
        --filter @create-font/preact-konva
        --filter @create-font/editor
