[tools]
"cargo:wasm-bindgen-cli" = "0.2.126"
ni = "30.5.0"
node = "26.8.0"
pnpm = "11.24.0"
rust = { version = "1.98.0", components = ["clippy", "rustfmt"], targets = [
	"wasm32-unknown-unknown",
] }
