export {
	analyzeFeaProject,
	lowerFeaSubstitutions,
	parseFea,
	parseFeaSyntax,
} from "./fea.ts"
export { FeaLineIndex, feaSyntaxTokensAtOffset } from "./fea-analysis.ts"
export type {
	AnalyzeFeaProjectInput,
	FeaAnalysisDiagnostic,
	FeaAnalysisDocument,
	FeaAnalysisParser,
	FeaProjectAnalysis,
	FeaProjectGlyph,
} from "./fea-analysis.ts"
export type {
	FeaDiagnostic,
	FeaDocumentAst,
	FeaFeatureAst,
	FeaParseResult,
	FeaSourceRange,
	FeaSubstitutionAst,
	FeaSyntaxDiagnostic,
	FeaSyntaxDocument,
	FeaSyntaxElement,
	FeaSyntaxNode,
	FeaSyntaxRange,
	FeaSyntaxToken,
	FeatureSubstitutionIr,
} from "./fea.ts"
export {
	canonicalizeEditorFontSource,
	decodeEditorFontSource,
	encodeEditorFontSource,
	fromEditorFontFile,
	toEditorFontFile,
	validateEditorFontSource,
} from "./codec.ts"
export {
	CREATE_FONT_SOURCE_FORMAT,
	CREATE_FONT_SOURCE_VERSION,
	assembleEditorFontSource,
	axisFileSchema,
	axisIdSchema,
	axisIndexFileSchema,
	axisUnitPathSchema,
	cmapEntryFileSchema,
	cmapIndexFileSchema,
	cmapUnitPathSchema,
	defaultAxisUnitPath,
	defaultCmapUnitPath,
	defaultGlyphUnitPath,
	defaultInstanceUnitPath,
	defaultMasterUnitPath,
	formatSourceUnit,
	featureIndexFileSchema,
	glyphFileSchema,
	glyphIdSchema,
	glyphIndexFileSchema,
	glyphUnitPathSchema,
	instanceFileSchema,
	instanceIdSchema,
	instanceIndexFileSchema,
	instanceUnitPathSchema,
	jsonSchemaForSourceUnit,
	masterFileSchema,
	masterIdSchema,
	masterIndexFileSchema,
	masterUnitPathSchema,
	metadataFileSchema,
	metricsFileSchema,
	namesFileSchema,
	pointIdSchema,
	parseSourceUnitText,
	projectFileSchema,
	sourceUnitKindForPath,
	sourceUnitDescriptors,
	splitEditorFontSource,
	styleFileSchema,
	validateSourceUnit,
	type AxisFile,
	type AxisIndexFile,
	type CmapEntryFile,
	type CmapIndexFile,
	type FontSourceDirectoryFiles,
	type FeatureIndexFile,
	type GlyphFile,
	type GlyphIndexFile,
	type InstanceFile,
	type InstanceIndexFile,
	type MasterFile,
	type MasterIndexFile,
	type MetadataFile,
	type MetricsFile,
	type NamesFile,
	type ProjectFile,
	type SourceUnitKind,
	type SplitFontSourceOptions,
	type StyleFile,
} from "./directory.ts"
export {
	CREATE_FONT_EDITOR_FORMAT,
	CREATE_FONT_EDITOR_VERSION,
	type EditorFontFile,
	type EditorFontFileMetadata,
	type SourceDiagnostic,
	type SourceDiagnosticCode,
	type SourceFailure,
	type SourceResult,
	type SourceSuccess,
} from "./types.ts"
