[package]
name = "create-font-fea-rs-wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
description = "WebAssembly bindings for fea-rs and create-font Adobe feature formatting"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
create-font-fea = { path = "../create-font-fea" }
serde_json.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
